create table if not exists public.ace_sales_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
alter table public.ace_sales_state enable row level security;
create policy "Users read own Ace state" on public.ace_sales_state for select using (auth.uid() = user_id);
create policy "Users insert own Ace state" on public.ace_sales_state for insert with check (auth.uid() = user_id);
create policy "Users update own Ace state" on public.ace_sales_state for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists public.ace_public_enquiries (
  id bigint generated by default as identity primary key,
  lead_id text not null unique,
  payload jsonb not null,
  imported boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.ace_public_enquiries enable row level security;
create policy "Anyone can submit an Ace enquiry" on public.ace_public_enquiries for insert to anon with check (true);
create policy "Signed-in user reads Ace enquiries" on public.ace_public_enquiries for select to authenticated using (true);
create policy "Signed-in user updates Ace enquiries" on public.ace_public_enquiries for update to authenticated using (true) with check (true);
